pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r code/* .public/
    - echo '<meta http-equiv="refresh" content="0; url=seiten/index.html" />' > .public/index.html
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH